spring.application.name=InstantMessenger

spring.datasource.url=jdbc:postgresql://localhost:5432/instantmessenger
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
logging.level.root=info
logging.file.name=app.log
spring.flyway.database-type-check=false
spring.flyway.baseline-on-migrate=true

# ===================================================================
# KONFIGURACJA RABBITMQ (Obsługa błędów i ponowień)
# ===================================================================
# 1. Włączamy automatyczne ponawianie prób przy błędzie
spring.rabbitmq.listener.simple.retry.enabled=true

# 3. Pierwsza ponowna próba po 2 sekundach
spring.rabbitmq.listener.simple.retry.initial-interval=2000ms

# 4. Każda kolejna próba czeka 2x dłużej (2s, potem 4s...)
spring.rabbitmq.listener.simple.retry.multiplier=2

# 5. Gdy 3 próby się nie powiodą, NIE wrzucaj wiadomości z powrotem do kolejki (zatrzymuje pętlę!)
spring.rabbitmq.listener.simple.default-requeue-rejected=false