spring.application.name=InstantMessenger

spring.datasource.url=jdbc:postgresql://localhost:5432/instantmessenger
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
logging.level.root=info
logging.file.name=app.log